# Generated by Django 2.2.4 on 2019-08-03 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber_of_seats', models.IntegerField(default=4, help_text='Enter namber of seats')),
                ('width_circle', models.FloatField(default=2.5)),
                ('height_circle', models.FloatField(default=2.5)),
                ('left', models.IntegerField(default=0, help_text='Position left')),
                ('top', models.IntegerField(default=0, help_text='Position top')),
                ('right', models.IntegerField(default=0, help_text='Position right')),
                ('bottom', models.IntegerField(default=0, help_text='Position bottom')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 3, 13, 6, 16, 889702, tzinfo=utc))),
            ],
        ),
    ]
