# Generated by Django 2.2.4 on 2019-08-03 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablelist',
            name='circle_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 3, 13, 27, 55, 462694, tzinfo=utc)),
        ),
    ]
