# Generated by Django 2.2.4 on 2019-08-03 14:42

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0005_auto_20190803_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablelist',
            name='height_circle',
        ),
        migrations.RemoveField(
            model_name='tablelist',
            name='width_circle',
        ),
        migrations.AddField(
            model_name='tablelist',
            name='email_client',
            field=models.EmailField(default=None, help_text='Customer Email for Booking Notification', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='tablelist',
            name='height_table',
            field=models.IntegerField(default=40, help_text='Table height, %', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tablelist',
            name='width_table',
            field=models.IntegerField(default=20, help_text='Table width, %', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 3, 14, 42, 22, 618813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='position_x',
            field=models.IntegerField(default=0, help_text='Position x. Origin in the upper left corner, %', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='position_y',
            field=models.IntegerField(default=0, help_text='Position y. Origin in the upper left corner, %', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
