# Generated by Django 2.2.4 on 2019-08-03 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0011_auto_20190803_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelist',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 3, 14, 54, 24, 49845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='email_client',
            field=models.EmailField(blank=True, default='test', help_text='Customer Email for Booking Notification', max_length=254, unique=True),
        ),
    ]
