# Generated by Django 2.2.4 on 2019-08-03 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0012_auto_20190803_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber_table', models.IntegerField(default=None, help_text='Enter namber of seats')),
                ('status', models.IntegerField(default=0, help_text='Enter status of table. 0 - free, 1 - booked')),
                ('email_client', models.EmailField(blank=True, default='test', help_text='Customer Email for Booking Notification', max_length=254, unique=True)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 3, 15, 6, 45, 144707, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='tablelist',
            name='email_client',
        ),
        migrations.RemoveField(
            model_name='tablelist',
            name='status',
        ),
        migrations.AddField(
            model_name='tablelist',
            name='namber_of_table',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 3, 15, 6, 45, 144707, tzinfo=utc)),
        ),
    ]
