# Generated by Django 2.2.4 on 2019-08-03 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0014_auto_20190803_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=0, help_text='Enter status of table. 0 - free, 1 select table, 3 - booked'),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='date_time',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 3, 15, 31, 20, 70981, tzinfo=utc)),
        ),
    ]
