# Generated by Django 2.2.4 on 2019-08-04 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0015_auto_20190803_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email_client',
            field=models.EmailField(blank=True, default='test', help_text='Customer Email for Booking Notification', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='date_time',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 4, 12, 8, 17, 698300, tzinfo=utc)),
        ),
    ]
