# Generated by Django 2.2.4 on 2019-08-05 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0016_auto_20190804_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email_client',
            field=models.EmailField(blank=True, default='test', help_text='Customer Email for Booking Notification', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tablelist',
            name='date_time',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 8, 5, 4, 50, 4, 444889, tzinfo=utc)),
        ),
    ]
